# Generated by Django 2.0.7 on 2018-08-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20180801_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, default='Add a description', max_length=3000),
        ),
    ]
