# Generated by Django 2.0.7 on 2018-08-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20180803_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name_plural': 'Groups'},
        ),
    ]
